# Generated by Django 4.0.6 on 2022-07-23 14:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='large_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='image file'),
        ),
    ]
