# Generated by Django 4.0.6 on 2022-07-24 15:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_large_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='large_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Upload images with a width of 2000px or greater to avoid low visual quality (e.g. pixelation) on larger screen sizes.', upload_to='', verbose_name='image file'),
        ),
    ]
