# Generated by Django 4.0.6 on 2022-07-30 14:18

import django.core.validators
from django.db import migrations, models
import photos.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(help_text='Enter a unique, descriptive URL path (e.g. based on the title) containing only lowercase letters, numbers,  and hyphens (instead of spaces). ', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), photos.models.validate_lowercase]),
        ),
    ]
