# Generated by Django 4.0.6 on 2022-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default='Photo description', max_length=5000),
            preserve_default=False,
        ),
    ]
