# Generated by Django 4.0.6 on 2022-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(default='Location', help_text='Enter the specific location where the photo was taken.', max_length=255),
            preserve_default=False,
        ),
    ]
