# Generated by Django 4.0.6 on 2022-08-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_country_photo_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
