# Generated by Django 4.0.6 on 2022-08-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
    ]
