# Generated by Django 4.0.6 on 2022-08-14 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateField(default=datetime.date(2022, 8, 14)),
            preserve_default=False,
        ),
    ]
