# Generated by Django 4.0.6 on 2022-08-14 13:27

import django.core.validators
from django.db import migrations, models
import photos.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='slug', help_text='Enter a unique, descriptive URL path (e.g. based on the name) containing only lowercase letters, numbers,  and hyphens (instead of spaces). ', unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), photos.models.validate_lowercase]),
            preserve_default=False,
        ),
    ]
