# Generated by Django 4.0.6 on 2022-08-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_photo_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
