# Generated by Django 4.0.6 on 2022-08-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_photo_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='collections',
            field=models.ManyToManyField(blank=True, to='photos.collection'),
        ),
    ]
