# Generated by Django 4.0.6 on 2022-10-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(help_text='Enter the clickable link text (anchor text).', max_length=50)),
                ('link_url', models.CharField(help_text="Enter the link destination relative URL. E.g. if the full URL is 'https://www.example.com/photos/this-photo' then the relative URL is '/photos/this-photo'.", max_length=255, verbose_name='link URL')),
                ('vertical_order', models.IntegerField(choices=[(0, 'N/A'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=0)),
            ],
        ),
    ]
