# Generated by Django 4.0.6 on 2022-10-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlink',
            name='vertical_order',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=0, help_text="Select the vertical ordering of the link in the dropdown menu (if applicable), where '1st' refers to the top position."),
        ),
    ]
