# Generated by Django 4.0.6 on 2022-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_alter_navlink_vertical_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_label', models.CharField(blank=True, help_text='Enter the clickable dropdown menu text, if applicable. Otherwise, leave blank if the navigation menu section contains only a single link rather than a dropdown menu.', max_length=50)),
                ('section_order', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th')], help_text="Select the ordering of the navigation menu section, where '1st' refers to the leftmost (desktop) or top (mobile) position.", unique=True)),
            ],
            options={
                'ordering': ['section_order'],
            },
        ),
    ]
