# Generated by Django 4.0.6 on 2022-10-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_navsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlink',
            name='nav_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nav.navsection'),
        ),
    ]
