# Generated by Django 4.0.6 on 2022-10-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0004_navlink_nav_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navlink',
            options={'verbose_name': 'Navigation Link'},
        ),
        migrations.AlterModelOptions(
            name='navsection',
            options={'ordering': ['section_order'], 'verbose_name': 'Navigation Section'},
        ),
    ]
