# Generated by Django 4.0.6 on 2022-10-23 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('message', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('contact_time', models.DateTimeField(auto_now_add=True)),
                ('responded_to', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-contact_time'],
            },
        ),
    ]
